= Vert.x Gradle Starter

This project is a template to start your own Vert.x project using Gradle with Groovy.

== Prerequisites

* JDK 8+

== Getting started

Create your project with:

[source]
----
git clone https://github.com/vert-x3/vertx-gradle-starter.git PROJECT_NAME
----

Replace `PROJECT_NAME` with the name of your project.

== Running the project

Once you have retrieved the project, you can check that everything works with:

[source]
----
./gradlew test vertxRun
----

The command compiles the project and runs the tests, then  it launches the application, so you can check by yourself. Open your browser to http://localhost:8080. You should see a _Hello World_ message.

== Anatomy of the project

The project contains:

* the Gradle project using the Groovy DSL (see `build.gradle`) with auto-reloading and fat-jar building
* a _main_ verticle file (`src/main/java/io/vertx/starter/MainVerticle.groovy`)
* a unit test (`src/main/test/io/vertx/starter/MainVerticleTest.groovy`)

== Start to hack

1. Delete the `.git` directory
2. Open the `build.gradle` file and customize `vertxVersion`. You can also change the `mainVerticleName` variable to use your own package name and verticle class.
3. Run `./gradlew vertxRun`.

This last command relaunches Gradle and the application as soon as you change something under `src/main`.

== Building the project

To build the project, just use:

----
./gradlew build
----

It generates a _fat-jar_ in the `build/libs` directory.